### ISSUE TITLE
Cannot load the resource

### ISSUE THREAD

**Issue by Se7enair** [olijouve/webrtc-streamer-card#1]
Got a failure when trying to add it to my lovelace.

```
Custom element doesn't exist: webrtc-streamer-card.
type: 'custom:webrtc-streamer-card'
entity: camera.garten_kamera_hof
name: garten_kamera_hof
stream_uri: 'rtsp://user:password@10.0.1.1:554/h264Preview_01_main'
webrtc_server_url: 'http://10.0.1.2:8000/'
```

Any ideas?

**Comment by Se7enair** [comment]
2021-02-16 08:17:57 ERROR (MainThread) [frontend.js.latest.202101277] http://192.168.178.7:8123/lovelace-admin/test:0:0 Uncaught
2021-02-16 08:18:33 ERROR (MainThread) [frontend.js.latest.202101277] http://192.168.178.7:8123/config/lovelace/resources:0:0 Uncaught

**Comment by Se7enair** [comment]
Logger: frontend.js.latest.202101277
Source: components/system_log/__init__.py:190
First occurred: 8:15:47 (18 occurrences)
Last logged: 8:18:33

http://192.168.178.7:8123/config/lovelace/resources:0:0 Uncaught
http://192.168.178.7:8123/lovelace-admin/test:0:0 Uncaught

**Comment by olijouve** [comment]
Did you added the module in your dashboard ressources ?

resources:
  - url: /local/webrtc-streamer-card/webrtc-streamer-card.js?v=0.1
    type: module

**Comment by Se7enair** [comment]
The first that I checked
![grafik](https://user-images.githubusercontent.com/1680106/108082287-386a3800-7072-11eb-8a92-e0a1b2abfb23.png)

**Comment by olijouve** [comment]
Did you restart HA ?

**Comment by Se7enair** [comment]
Did this a few times. Also double and triple checked everything.

lovelace-card
```
type: 'custom:webrtc-streamer-card'
entity: camera.garten_kamera_hof
name: garten_kamera_hof
stream_uri: 'rtsp://user:passwd@10.0.1.1:554/h264Preview_01_main'
webrtc_server_url: 'http://10.0.1.2:8000/'
```
Resources are loaded, see picture above

Files
![image](https://user-images.githubusercontent.com/1680106/108121424-16d57480-70a3-11eb-9ffd-6529727fab9c.png)

![image](https://user-images.githubusercontent.com/1680106/108121453-21900980-70a3-11eb-9b1b-891a7215e585.png)


I dont know if the webrtc server is working correctly, but this should not affect the card right?

**Comment by exotsk** [comment]
i have the same. i suppose it`s depend on path "import" in js files. i trying different paths, with restart everytime but Custom element doesn't exist:

**Comment by andrew-yu** [comment]
> i have the same. i suppose it`s depend on path "import" in js files. i trying different paths, with restart everytime but Custom element doesn't exist:

same

**Comment by andrew-yu** [comment]
Real card name is 'custom:rtsp-webrtc-card'?!

**Comment by Se7enair** [comment]
> Real card name is 'custom:rtsp-webrtc-card'?!

Does this work for you?

**Comment by andrew-yu** [comment]
@Se7enair yes and no. Custom card is working now, but i have issues with webrtc-streamer docker container to stream anything. I installed it with Portainer addon, but I've got little experience with Docker at all...

None of the demo streams of webrtc-streamer's web interface at http://my-local-ip:8000/ are working now.

Upd: demo streams work in Google Chrome at Android, but not in Windows PC.

**Comment by Se7enair** [comment]
@andrew-yu did you changed any other things, except the name of the card in lovelace?

Edit: got a typo in the resource. Now it is working with the new name. Will check with stream.

**Comment by Se7enair** [comment]
Demo stream is working on desktop chrome and directly in homeassistant.
When I change to camerastream it wont. The stream uri is correct, because it is working in vlc.

Does this need any specific settings in the stream?

**Comment by andrew-yu** [comment]
Still can't get camera stream, which works (with delay) with default ha component.

**Comment by Se7enair** [comment]
It is working now. There was a firewall problem. Had to allow the webrtc server to connect to the camera.

The solution for the inital problem was mentioned from @andrew-yu 

> Real card name is 'custom:rtsp-webrtc-card'?!

Will close this.

@andrew-yu please open a new issue to keep this clean
